### ISSUE TITLE
Mutation not working

### ISSUE THREAD

**Issue by akmanoj** [SimonCropp/GraphQL.EntityFramework#10]
It throw expection
'Introspection must provide output type for fields.' on fields

**Comment by SimonCropp** [comment]
Graphql mutations are required to return at least one field. Even if it is not used. So r u including a field ?

**Comment by akmanoj** [comment]
where to include can you give some example?

**Comment by akmanoj** [comment]
` Field<CustomerInputType>(
                  "createCustomer1",
                  arguments: new QueryArguments(
                  new QueryArgument<NonNullGraphType<CustomerInputType>> { Name = "customer1" }
            ),
            resolve: context =>
            {

                var customer = context.GetArgument<Customer>("customer");
                using (var dbContext = new CommonServiceContext(

           serviceProvider.GetRequiredService<DbContextOptions<CommonServiceContext>>()))
                {
                    dbContext.Customers.Add(customer);
                    return dbContext.SaveChangesAsync();
                }

            });`

 if i add return type like this `Field<CustomerInputType,Customer>` it is giving error in arguments.

**Comment by SimonCropp** [comment]
i am new as well. Note that this project is about querying data. not mutations. or more specifically i have not invested any time working out how mutations apply to EF

So the graphql doco for mutations is here https://graphql-dotnet.github.io/docs/getting-started/mutations

and there is a runnable mutation sample in this https://github.com/graphql-dotnet/examples/ ...  https://github.com/graphql-dotnet/examples/blob/master/src/StarWars/StarWarsMutation.cs

**Comment by akmanoj** [comment]
Ok. Thanks.
