### ISSUE TITLE
Issue in documentation

### ISSUE THREAD

**Issue by PayteR** [SimonCropp/GraphQL.EntityFramework#104]
Hi, In the documentation is written
```
There is a helper methods to perform the above:

EfGraphQLConventions.RegisterConnectionTypesInContainer(IServiceCollection services);
```
https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/pages/configuration.md

But there is not such a helper
![image](https://user-images.githubusercontent.com/1248565/54710744-a2a59580-4b48-11e9-90a5-bcd2aaf8ca2b.png)

Could you please add this helper? Or can you point me, how to register that as action? thx

**Comment by SimonCropp** [comment]
sorry  i re added this and deployed it.

Note that when version 3 of graphql-dotnet is released this will no longer be required https://github.com/graphql-dotnet/graphql-dotnet/pull/1039
