### ISSUE TITLE
QueryPaginationField proposal

### ISSUE THREAD

**Issue by PayteR** [SimonCropp/GraphQL.EntityFramework#106]
Hi, 
i really like your implementation of query fields and query connection fields but i miss something in the middle - I need to paginate query field results, but there are no pageinfo meta for that purpose. I came from PHP (Laravel) enviroment and there pagination is implemented into GraphQL like this:

![image](https://user-images.githubusercontent.com/1248565/54773446-e14f5480-4c09-11e9-9dc6-d53e9f48713f.png)

I imagine it somehow similar, query variables like this:
![image](https://user-images.githubusercontent.com/1248565/54774601-6f2c3f00-4c0c-11e9-86ce-1e58d9341e72.png)

And inside that, it could be like this:
```
queryname {
	items: {
		.
		.
		.
	},
	totalCount
	perPage
	currentPage
	from
	to	
}
```

What do you think about this proposal, would you merge it if i make some PR?

**Comment by SimonCropp** [comment]
i think this would be ok. i would need to see the PR to be certain

**Comment by SimonCropp** [comment]
Bump

**Comment by PayteR** [comment]
Hi, i want to do that, but i don't have a time right now. Maybe next week.

**Comment by skoruba** [comment]
This will be really useful, I have a similar use case. 👍

**Comment by SimonCropp** [comment]
@skoruba @flieks note that you should patron to be using this project https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/pages/licensing-patron-faq.md

**Comment by flieks** [comment]
@SimonCropp your link is broke. Maybe you meant https://opencollective.com/graphqlentityframework. 

Just a note:
I'm not using this lib at the moment but maybe i will in the future.
I still don't understand why this project has not more attraction as it's way easier then using dataloader i think. 
For the moment i'm using prisma (node) but if this lib would have some more feature (for example sql sum()) then i would probably switch.

Keep up the good work..

**Comment by SimonCropp** [comment]
@flieks link fixed

**Comment by SimonCropp** [comment]
@PayteR still interested in doing a PR here?

**Comment by PayteR** [comment]
@SimonCropp still didn't have time to do that, i will get into it eventually but if you wan't to do that you don't need to wait for me
