### ISSUE TITLE
Lacking fragment support

### ISSUE THREAD

**Issue by chris-nissen** [SimonCropp/GraphQL.EntityFramework#11]
This doesn't support fragments, it seems. Would it be a hard feature to add?

**Comment by SimonCropp** [comment]
what exactly do you mean by "doesn't support fragments". my understanding of fragments is they dictate from the client side a group of fields. how would that map to the server side?

perhaps upload a small repro that show what you are trying to achieve

**Comment by SimonCropp** [comment]
Tbh i have not had a need to use fragments in that way, so have not invested the time in adding support.

Happy to accept a PR that adds support

**Comment by chris-nissen** [comment]
If we really need fragments, I may work on a PR.
