### ISSUE TITLE
Auto generate graphtypes

### ISSUE THREAD

**Issue by morgul77** [SimonCropp/GraphQL.EntityFramework#12]
Hi

I just started looking at graphql, and started with the core library.
I quickly went on to https://github.com/graphql-dotnet/conventions, which was pretty nice to include all types without typing them out. 

But, it's not very dynamic, and therefore trying this library, and I got it working very nicely.

However, the generation of the graphtypes like the conventions library does would be nice.

Has any work been done on that? Or am I missing something? 

Any hints or hurdles I may bump into that you know about?

If I make a stab at it, is depending on the conventions library the wrong way to go?

**Comment by SimonCropp** [comment]
> Has any work been done on that? Or am I missing something?

Nope no work has been done in this area

> Any hints or hurdles I may bump into that you know about?

not that i know of

> If I make a stab at it, is depending on the conventions library the wrong way to go?

yeah this project should only depend on the main GraphQL nuget. reasons:

 * reduce the risk of conflicts when updating.  eg when GraphQL relwease a new breaking change, if this lib depended on GraphQL.Conventions, then  this lib would need to wait for conventions to update prior to releasing a new version
 * it is possible for multiple different convention libs to exists, each taking a unique and opinionated approach. 

If GraphQL.Conventions ever merges with GraphQL then it would be op to re-use those types

I would have though that GraphQL.Conventions supported overriding conventions with code, which would allow you to use `IEfGraphQLService` to add fields based on a convention?

**Comment by SimonCropp** [comment]
Closed due to no response.

**Comment by isabekyan** [comment]
Hi, I've made a simple implementation of Graph Types and Query auto-generation based on EF Core context/model. Right now it consists of 2 classes only that I host in my own project.
I'd like to contribute it if you are interested, are u?) It'll need some discussion on design I think.

**Comment by SimonCropp** [comment]
Yep, I am interested in the possibility of adding this functionality

**Comment by isabekyan** [comment]
Here's my current code to start discussion from: [autoconfig](https://github.com/isabekyan/GraphQL.EntityFramework/tree/autoconfig/src/GraphQL.EntityFramework/AutoConfig)
Basic idea is to get all db sets from ef context and set them as root queries. All types are configured based on injected IModel of the context, all ef properties and navigations are configured.
Configuration required:
`services.AddSingleton(context.Model);
services.AddSingleton(typeof(EfEntityGraph<>));
services.AddSingleton(typeof(EnumerationGraphType<>));`
Thoughts?

**Comment by MartinRisk** [comment]
Any news on this functionality ?

**Comment by SimonCropp** [comment]
the base graph type now has an `AutoMap` function that generates mappings based on EF navigations. it is in the current beta on nuget
