### ISSUE TITLE
Resolving Query Connection Fields Makes Suboptimal Database Access

### ISSUE THREAD

**Issue by nlordell** [SimonCropp/GraphQL.EntityFramework#132]
I was evaluating this project for an upcoming project and found some places where suboptimal database access was being made.

Consider a simple setup where (omitting a lot of boilerplate code):
```cs
    public class MyContext : DbContext
    {
        public DbSet<MyItem> Items { get; set; }
    }

    public class MyItem
    {
        public int Id { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
    }

    public class MyQuery : EfObjectGraphType
    {
        public MyQuery(IEfGraphQLService gql, MyContext db)
            : base(gql)
        {
            AddQueryConnectionField(
                name: "allItems",
                resolve: context => db.Items);
        }
    }
```

Performing a simple GraphQL query:
```graphql
{
    allItems { totalCount }
}
```

Will cause the following database queries to be made by EF Core:
```
SELECT COUNT(*)
FROM "Items" AS "i"

SELECT "i"."Id", "i"."A", "i"."B", "i"."C"
FROM "Items" AS "i"
LIMIT @__p_1 OFFSET @__p_0
```

From what I gathered from looking at the source, this is because when resolving the `Connection<MyItem>` there is no optimization being made to not query the list of items when neither `edges { node }` nor `items` is selected. I would expect only the following database query to be made:
```
SELECT COUNT(*)
FROM "Items" AS "i"
```

In the same vein the following query will needlessly retrieve the total count (with a `SELECT COUNT(*)...` database query):
```graphql
{
    allItems { items { id } }
}
```

In fact, for the aforementioned query, I would expect the only following database query to be made by EF Core:
```
SELECT "i"."Id"
FROM "Items" AS "i"
LIMIT @__p_1 OFFSET @__p_0
```

Unfortunately, however, when resolving the `Connection<MyItem>` the entire entity is being loaded (with tracking, `.AsNoTracking()` can be specified manually in the `EfObjectGraphType` implementation on the `AddQueryConnectionField` call but I imagine it is a sane default to have) instead of just the required properties. This can be achieved in EF Core with something like following, where the result will only contain the `Id` property set and have leave the other properties unset:

```cs
using (var context = new MyContext())
{
    var result = await db.Items
        .Select(i => new MyItem
        {
            Id = i.Id
        })
        .ToListAsync();
}
```

The above code would result in the following database query being generated by EF Core:
```
SELECT "i"."Id"
FROM "Items" AS "i"
```

Furthermore, this can be done programmatically with `Expression` with something like the following example being as far as I can tell exactly equivalent to the previous operation:
```cs
using (var context = new MyContext())
{
    var itemParameter = Expression.Parameter(typeof(MyItem), "i");
    var idProperty = typeof(MyItem).GetProperty("Id");
    var expression = Expression.Lambda<Func<MyItem, MyItem>>(
        Expression.MemberInit(
            Expression.New(typeof(MyItem)),
            Expression.Bind(
                idProperty,
                Expression.MakeMemberAccess(itemParameter, idProperty))),
        itemParameter);
    var result = await context.Items
        .Select(expression)
        .ToListAsync();
}
```

I have not tested this with navigation collection connections so I do not know whether it has the same issues but from quickly glancing at the code it seems to.

I did some quick and dirty benchmarking using an SQLite database (**disclamer** these are probably not valid or accurate benchmarks and are just for illustrative purposes - code provided in [this gist](https://gist.github.com/nlordell/55af139d88f3f78866e5172667d10cba)).  Using expressions to read only the `Id` property from the database is roughly 270% faster than retrieving an entire entity with tracking (what is currently being done) but only 40% faster than retrieving an entire entity without tracking (this should definitely be suggested in the documentation). However, retrieving the entire entity using expressions (so an `Expression.Bind` per property) is roughly 15% slower than just retrieving the entire entity untracked. 

This feature would probably require quite a lot of work and is something I would not be able to commit to. I decided to just post my findings here in case someone else was interested in optimizing implementing these features or funding their development.

**Comment by SimonCropp** [comment]
can you share a failing unit test as a Pull Request

**Comment by SimonCropp** [comment]
@nlordell bump

**Comment by nlordell** [comment]
As I mentioned in my issue request I am not in a position to do any work on this. I just wanted to post my findings from evaluating this project in case someone else wants to pick up the work.

**Comment by Shane32** [comment]
I've detected the same issue, but it also occurs with other queries in EF apart from GraphQL.  Typically I manually tweak the EF query for optimal execution, which obviously isn't possible here.  I'll be waiting until EF Core 3.0 drops, which will vastly improve the LINQ to SQL conversion, and then test the GraphQL library again to see if utilizing EF Core 3.0 fixes all the issues.

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/features
