### ISSUE TITLE
Suggestion: Remove ConfigureAwait(false)

### ISSUE THREAD

**Issue by Shane32** [SimonCropp/GraphQL.EntityFramework#186]
I read up on ConfigureAwait(false).  Honestly, I'm not sure how it's a benefit.  Asp.Net Core doesn't maintain a synchronization context, so it's completely redundant in that environment, both for speed and deadlocks.  And if it was used with .Net MVC Framework, you would lose access to HttpContext.Current, which would be very important for security code such as I've used in the past (necessary while resolving the graphs), so it may not be desirable.  And so long as GraphQL.EF is coded correctly, there would be no deadlocks within the code, so you're only patching other people's errors.  I'd recommend removing it.

https://www.skylinetechnologies.com/Blog/Skyline-Blog/December_2018/async-await-configureawait

https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

I'd also recommend adding Async methods throughout (anywhere there is a resolve parameter), so people can code without synchronous calls in an asynchronous context.  I can write a pull request if you agree.  I was going to suggest this anyway, as I already ran into a need for it.

- I am a patron under company name of Zbox

**Comment by Shane32** [comment]
In order to remove ConfigureAwait(false), all calls to Task.FromResult should be removed and replaced with functions that operate in a synchronous manner.  For instance, the synchronous version of AddSingleField should call a synchronous version of BuildSingleField.

**Comment by SimonCropp** [comment]
I think you are conflating task.Result with Task.GetResult

**Comment by Shane32** [comment]
You're right, of course.  Whoops!

**Comment by SimonCropp** [comment]
i think given i dont know who could be calling this lib, and i dont know if there is a context to capture, the ConfigureAwait should be kept

**Comment by Shane32** [comment]
Yeah, also I found that the GraphQL library uses ConfigureAwait extensively.  So it would be natural to keep it in your library.

**Comment by SimonCropp** [comment]
Yeah i think most libs use it just in case
