### ISSUE TITLE
AddNavigationField on a many-to-many relationship (via a cross table)

### ISSUE THREAD

**Issue by elertan** [SimonCropp/GraphQL.EntityFramework#19]
I have 2 entities (`Track` and `Album`) that have a many-to-many relationship via a cross table (`TrackXAlbum`) which works great, but not as a navigation field.

`AddNavigationField` expects the lambda to resolve with the provided type of entity given as the second generic type parameter, which can only be resolved by using a .`Select` call on the `IQuerable` instance returned by the `Where` call.

Example on the `AlbumGraph`:
```cs
AddNavigationField<TrackGraph, Track>(
      "tracks",
      resolve: ctx => db.TrackXAlbums.Where(e => e.AlbumId == ctx.Source.Id).Select(e => e.Track)
);
```

Which causes the exception:
`GraphQL.ExecutionError: Error trying to resolve albums. ---> System.NullReferenceException: Object reference not set to an instance of an object.`

I ended up using the `AddQueryField` method instead of the `AddNavigationField`. Which does work, but with a very big performance impact. Probably due to the `Select` call.

How would I go about a many-to-many relationship using the `AddNavigationField` method, or do I need to use a different method?

**Comment by SimonCropp** [comment]
Can u upload a small repro so i can debug into this

**Comment by SimonCropp** [comment]
re your repro. i didnt think EF could derive many to many by only convention

> The join table will be named after the join entity by convention. The relationship also needs to be configured via the Fluent API for EF Core to be able to map it successfully:

https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration

**Comment by SimonCropp** [comment]
also i think there is something wrong with your root query

![image](https://user-images.githubusercontent.com/122666/47253183-b1a1f200-d49b-11e8-8e7f-dfa1cff813f0.png)

**Comment by elertan** [comment]
> re your repro. i didnt think EF could derive many to many by only convention
> 
> > The join table will be named after the join entity by convention. The relationship also needs to be configured via the Fluent API for EF Core to be able to map it successfully:
> 
> https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration

I will attempt to use this style of configuring the relationship instead, and report it here if that worked out 😄 . Thanks!

**Comment by elertan** [comment]
> also i think there is something wrong with your root query
> 
> ![image](https://user-images.githubusercontent.com/122666/47253183-b1a1f200-d49b-11e8-8e7f-dfa1cff813f0.png)

Are you referring to the empty collection? If not, could you elaborate?

**Comment by SimonCropp** [comment]
> Are you referring to the empty collection? 

yep. 

does the in mem data store support reusing data that has been added in a disposed context? ie u create, add data, and dispose of the datacontext at startup. 

TBH i think for this type of repro u r better served by using sql server.

could u also try and add your many to many scenario to the integration tests as a Pull Request. https://github.com/SimonCropp/GraphQL.EntityFramework/tree/master/Tests/IntegrationTests  it would make it easier to debug and verify any fix

**Comment by elertan** [comment]
> > Are you referring to the empty collection?
> 
> yep.
> 
> does the in mem data store support reusing data that has been added in a disposed context? ie u create, add data, and dispose of the datacontext at startup.
> 
> TBH i think for this type of repro u r better served by using sql server.
> 
> could u also try and add your many to many scenario to the integration tests as a Pull Request. https://github.com/SimonCropp/GraphQL.EntityFramework/tree/master/Tests/IntegrationTests it would make it easier to debug and verify any fix

You're probably right on that, I just read the docs real quickly and it said that you can name these instances to share the same data. And for sql server, I'm currently developing on Mac OS without a some containerization features, to keep my project as simplistic as possible (university project), so I don't have sql server available to me, we're working with a Postgres db instead, and I figured the least amount of dependencies for a repro would be best, thus using the in memory db (which ended up doing nothing).

I'll attempt your suggestion soon, and see if that fixes it, and I'll  add a test afterwards via a PR.

Thanks for the help so far!

**Comment by SimonCropp** [comment]
in that case, i think with the inmemory u would need a single instance of the data context that u keep in memory and dont dispose

**Comment by elertan** [comment]
Haha, I just couldn't figure out straight away how to grab the instance from the dependency injector manually 😅 , and I wasn't able to register the instance itself, just the type as a service.

I'll look into it.

**Comment by SimonCropp** [comment]
put the instance into a static field, then inject that into the container

**Comment by elertan** [comment]
As you might've noticed I've added the integration test, and this repo's repro to include the changes you've suggested. Feel free to take a look : ). @SimonCropp
