### ISSUE TITLE
Visual Studio Solution - Demo

### ISSUE THREAD

**Issue by plwade** [SimonCropp/GraphQL.EntityFramework#205]
Hi Simon,
I have front end Angular skills, but limited back end .NET knowledge.
Is there any chance you could provide a working demo of your GraphQL.EntityFramework package, so that I can evaluate and decide if we can use it in our project.

Any help appreciated.

Regards,
Paul

**Comment by Shane32** [comment]
The source code includes a SampleWeb project, which contains a basic demonstration of the functionality

**Comment by SimonCropp** [comment]
@plwade there is nothing specific to this project that would effect the combination of angular and graphql. so you can use any example eg https://www.apollographql.com/docs/angular/recipes/simple-example/. this project conforms to the graphql spec so can be used in any sample.
