### ISSUE TITLE
Predicates - doubt

### ISSUE THREAD

**Issue by theanaoliveira** [SimonCropp/GraphQL.EntityFramework#219]
Hi!
I wonder if the predicates are applied after or before getting the data from the database.
I'm studying your project and I don't understand this part :(

Another thing, if I use your project in my project, all predicates be available? 

I really like that form you building this part

**Comment by SimonCropp** [comment]
* [Queries](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/query-usage.md) are done as a expressions that are passed to the DB. So only data matching the query is returned from the db.
 * [Filters](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/filters.md) are applied after the data has been returned from the DB

> Another thing, if I use your project in my project, all predicates be available?

not sure what you mean by this?

**Comment by theanaoliveira** [comment]
> * [Queries](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/query-usage.md) are done as a expressions that are passed to the DB. So only data matching the query is returned from the db.
> * [Filters](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/filters.md) are applied after the data has been returned from the DB
> 
> > Another thing, if I use your project in my project, all predicates be available?
> 
> not sure what you mean by this?

My last doubt if is the nuget package contains all predicates, like where, orderby, take

I added the package to my solution, and I'm study this part

**Comment by SimonCropp** [comment]
the nuget does have where, orderby, take
