### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Intecpsp** [SimonCropp/GraphQL.EntityFramework#231]
I have a working web service running 6.5.0 and just realized 7.1.0 is out. Usually major number increments means it's a breaking update. I don't want to blindly update and can't seem to find a list of changes. Is there a changelog to look over everything? If not, this needs to be a thing!

**Comment by aladd04** [comment]
I blindly updated in a branch to see if it would at least compile and it does not. I tried fixing the compilation errors, but the docs don't seem to be up-to-date to match what the code shows. I agree, this should be a thing.

**Comment by SimonCropp** [comment]
sorry i am not going to get this this. i simply dont have time. the doco is now up to date with the current release. I will try to do better on future release. Becoming a back would help https://opencollective.com/graphqlentityframework
