### ISSUE TITLE
Is there a way to achieve OR functionality?

### ISSUE THREAD

**Issue by PeymanDinani** [SimonCropp/GraphQL.EntityFramework#232]
I know where statements are [and'ed](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-and-operator-). I was wondering if there is any way to achieve [OR ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-or-operator-) functionality?

Example in LINQ to SQL:

```csharp
string phoneNumber = "1234567890";
People.Where(person => person.Phone1 == phoneNumber ||
                    person.Phone2 == phoneNumber ||
                    person.Phone3 == phoneNumber )
```

**Comment by Intecpsp** [comment]
You can use the 'in' comparison found [here](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/query-usage.md#supported-comparisons)

**Comment by SimonCropp** [comment]
no currently. happy to consider a PR that adds this functionality

**Comment by SLGShark6** [comment]
I'm working on a PR that adds Grouped Where expressions with a connector argument "or" or "and" such as where: [
      {groupedExpressions: [
        {path: "content", comparison: "contains", value: "4", connector: "or"},
      	{path: "content", comparison: "contains", value: "2"}
      ], connector: "and"},
      {path: "age", comparison: "greaterThanOrEqual", value: "31"}
  	]
