### ISSUE TITLE
Where 'value' should be able to read property values

### ISSUE THREAD

**Issue by Intecpsp** [SimonCropp/GraphQL.EntityFramework#236]
If I have a query like this:

`{
    provider {
        primaryAddressType
        addresses {
            type
        }
    }
}`

I should be able to use 'Provider.PrimaryAddressType' in my 'addresses' where clause so that I only get 1 address record instead of all associated to the provider based off another id in the table. Since the child query is evaluated and ran AFTER the parent, this data should be in the object for reading. 

The 'path' currently supports this as shown here: https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/query-usage.md#property-path

**Comment by SimonCropp** [comment]
please share a failing unit test as a PR
