### ISSUE TITLE
Paging with Connections - Clarifications about cursors

### ISSUE THREAD

**Issue by DelattreAdixon** [SimonCropp/GraphQL.EntityFramework#26]
GraphQL.EntityFramework implementation for paging with Connection model seems to use cursor sequence like "0", "1", "2", ...

Assuming a pagination with 100 items and paging with 10 items per page
I would like to implement feature like "**Go directly to page 7**".

Is it safe and reliable to assume I can query directly with arguments (first:10, after: X) where **X is computed mathematically** ?

I'm aware this is a workaround and only possible because of the cursor sequence. It would not work  Facebook approach (documentation about Connection Model, show examples with base64 string for cursor : https://graphql.github.io/learn/pagination/)

**Comment by SimonCropp** [comment]
@gbiellem thoughts?

**Comment by SimonCropp** [comment]
@DelattreAdixon i dont object to this approach. how about a PR?
