### ISSUE TITLE
ApplyGraphQlArguments IEnumerable

### ISSUE THREAD

**Issue by haris-begluk** [SimonCropp/GraphQL.EntityFramework#266]
ApplyGraphQlArguments method that accepts IEnumerable and returns iEnumerable  list of data 
When it will be called? I can see that we have Skip and Take arguments that supports Queryable.Take/Skip and Enumerable.Take/Skip, but when this kind of implementations will be used , when IEnumerable method will be called and when IQueryable,  if i send query like: 
query Where {
  posts(take:2, skip: 1,where: {
    path: "id",
    comparison: "in",
    value: ["00016", "00191","00232"]}) {
    id
   category
    language
    content
    updated
    updatedBy
  }
}

**Comment by SimonCropp** [comment]
did you read the issue template?

**Comment by haris-begluk** [comment]
> did you read the issue template?
Yes, but could not find answer.

**Comment by SimonCropp** [comment]
https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/defining-graphs.md#argumentprocessor
