### ISSUE TITLE
Can't run successfully

### ISSUE THREAD

**Issue by zsjbsn** [SimonCropp/GraphQL.EntityFramework#27]
Code in startup.cs like this(modified according to sample):

`var optionsBuilder = new DbContextOptionsBuilder<NHLStatsContext>();
            optionsBuilder.UseMySql(Configuration["ConnectionStrings:Default"], b => b.MigrationsAssembly("NHLStats.Api"));
            services.AddDbContext<NHLStatsContext>(options => options.UseMySql(Configuration["ConnectionStrings:Default"], b => b.MigrationsAssembly("NHLStats.Api")));
            EfGraphQLConventions.RegisterConnectionTypesInContainer(services);
            using (var myDataContext = new NHLStatsContext(optionsBuilder.Options))
            {
                EfGraphQLConventions.RegisterInContainer(services, myDataContext);
            }`

Errors:

![image](https://user-images.githubusercontent.com/13334530/48324529-0e906280-e66c-11e8-8a58-41a41831a6a6.png)

**Comment by SimonCropp** [comment]
Did u read the issue template 
https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md ?
