### ISSUE TITLE
netstandard2.0 compatibility

### ISSUE THREAD

**Issue by Intecpsp** [SimonCropp/GraphQL.EntityFramework#271]
Does this project need to be on netstandard2.1? I'm using this package (v 8.0.0) without the option of upgrading to core 3.0 to get the new features and bug fixes. If there aren't any netstandard2.1/core3.0 features being used can the project be downgraded back to 2.0/2.2? Or have a separate branch that is built for those versions?

**Comment by SimonCropp** [comment]
EF Core 3.0 targets netstandard 2.1. so i needed to update to add compat for that version

**Comment by SimonCropp** [comment]
BTW if you are a use why are you not a patron? https://github.com/SimonCropp/GraphQL.EntityFramework#community-backed

**Comment by Intecpsp** [comment]
But does the project need to be 3.0 compatible? It's brand new on the market and I don't see many enterprises making that migration for at least 6 months. Core 2.2 is the current mainstream standard, and since migrating to 3.0, anybody left on 2.2 won't get any new features or bug fixes for this library. As for becoming a patron, I'm actually using this library at the company I work at, so me being a patron doesn't make sense.

**Comment by Intecpsp** [comment]
I actually just came across this: https://github.com/SLGShark6/GraphQL.EntityFramework/tree/core-2-compatible-branch

@SLGShark6

**Comment by SimonCropp** [comment]
> I'm actually using this library at the company I work at, so me being a patron doesn't make sense.

in that case all devs at your company should be patrons. https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/licensing-patron-faq.md#organization-licensing

> But does the project need to be 3.0 compatible? 

yes it does. being v3 compat does not stop you using an older (v2 compat) version. but not being v3 compat stops any people wanting to use the current stable version in their apps. and there have been almost 400000 downloads of the v3 package, so there must be a non trivial number of real consumers.

> I don't see many enterprises making that migration for at least 6 months

The enterprise org i work at has already upgraded and will be deploying this week

> Or have a separate branch that is built for those versions?

This would be a reasonable amount of work. Unless more people become patrons, or someone offers funding to work on it, i cant justify the effort.

**Comment by Intecpsp** [comment]
I will forward that licensing link to my superiors and have them figure out how to proceed from that standpoint. What about pulling in that core 2 branch I linked above?

**Comment by SimonCropp** [comment]
> What about pulling in that core 2 branch I linked above?

Are you willing to put in the effort to keep a v2 branch updated? ie regularly pulling changes from master and submitting a PR to the v2 branch?

**Comment by Intecpsp** [comment]
It seems like @SLGShark6 is already doing that.

**Comment by SimonCropp** [comment]
@Intecpsp that branch is 23 commits ahead, 41 commits behind master. and none of those changes are being submitted back as a releasable PR

how many developers are on your team?

**Comment by SimonCropp** [comment]
looks like ef 3.1 is going to target netstandard 2.0. so i will evaluate re-targeting netstandard 2.0 
https://github.com/aspnet/EntityFrameworkCore/issues/18141

**Comment by SimonCropp** [comment]
i have released 9.3.0-beta.1 that targets EF3.1 and re adds netstandard 2 support

**Comment by SimonCropp** [comment]
there is now a stable on nuget that supports netstandard 2.0
