### ISSUE TITLE
graphql-dotnet's dataloader compatible

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#3]
Hi,

This is awesome and super helpfull but can it work in combination with dataloader ?

**Comment by flieks** [comment]
Hi Simon,

Thanks, but batching is really important (not for updating but for querying). Data Loader is solving that problem and batches the sql queries to retrieve data in 1 sqlCommand. 
For example you want to get 3 orders, each have a customer resolver. The resolver will be executed 3 times => 3 sqlCommands executed. With dataLoader it will execute 1 command and put a `where CustomerId in [id1, id2, id3]`

**Comment by SimonCropp** [comment]
that can be done in this project by applying a `where` on the nested node https://github.com/SimonCropp/GraphQL.EntityFramework#single-1 and then the include nodes behaviour will handle making all the call being returned in the root query https://github.com/SimonCropp/GraphQL.EntityFramework#includes-and-navigation-properties

**Comment by flieks** [comment]
applying a where on the request query isn't ideal as the resolver should resolve the object based on the parent node.

So the includes use the EF eager loading by default ? So then all commands (from all resolvers) are batched in 1 command or how does this work ?

**Comment by SimonCropp** [comment]
> For example you want to get 3 orders, each have a customer resolver. The resolver will be executed 3 times => 3 sqlCommands executed. 

no

if u request 3 orders, and have also asked for the customer of those orders. the initial query to EF will use `.Include("Customer")`. So the 3 customers will be returned as part of the initial (and single) request to the db

**Comment by SimonCropp** [comment]
seems this has been adequately answered
