### ISSUE TITLE
Clarify what the project does in README

### ISSUE THREAD

**Issue by Sigvaard** [SimonCropp/GraphQL.EntityFramework#30]
There's already a similar project here: https://github.com/ckimes89/graphql-net (seems to be older than yours)

How would you compare it? Is it an alternative to the project above? Or it does something different?

> Add EntityFramework Core IQueryable support to GraphQL

 in readme doesn't tell much.

Also it would be helpful to have some kind of quickstart, how to get started without looking at the example project.

**Comment by SimonCropp** [comment]
the difference is in the the text u posted

` support to [GraphQL](https://github.com/graphql-dotnet/graphql-dotnet)`

ie this project builds on and co-operates with an existing graphql library.

**Comment by SimonCropp** [comment]
also when i checked https://github.com/ckimes89/graphql-net  back in october it seemed abandoned. over 12 months with no commit, no net standard support, there is still no nuget release for over 18 months, many issues not being addressed.

Given https://github.com/graphql-dotnet/graphql-dotnet provided the majority of the functionality we needed, and an extensible API that allowed us to plug in EF support, and it was active, we went that way instead

**Comment by SimonCropp** [comment]
@Sigvaard with the above in mind, can u suggest some modifications to the readme that adds some clarity?
