### ISSUE TITLE
Non Generic AddQueryField

### ISSUE THREAD

**Issue by dxramax** [SimonCropp/GraphQL.EntityFramework#32]
Is there any way to add query field and resolve the context without relying on a generic implementation.

I need to call `AddQueryField` and resolve the data context using non generic class [`DbContext`](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext?redirectedfrom=MSDN&view=entity-framework-6.2.0) which return non generic [`DbSet`](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset?view=entity-framework-6.2.0).

I have read the file [EfGraphQLService_Queryable.cs](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/0917e0f4686cc4b7941a48e91568df17813e5890/GraphQL.EntityFramework/EfGraphQLService_Queryable.cs) and all `AddQueryField` overloads should at least specify the return type at compile time.

**Comment by dxramax** [comment]
I have used reflection to call the generic function, but it would be nice if we call it with no generic parameters.

**Comment by SimonCropp** [comment]
happy to consider a pull request for this one
