### ISSUE TITLE
Queries with fragments and nested fields don't produce the correct joins/data

### ISSUE THREAD

**Issue by timstokman** [SimonCropp/GraphQL.EntityFramework#377]
#### Describe the issue

Queries that use fragments and nested fields don't join/retrieve the correct data.

#### Minimal Repro

The SampleWeb project (https://github.com/SimonCropp/GraphQL.EntityFramework/tree/master/src/SampleWeb) can be used for reproducing the issue.

This works:

```
query {
  companies {
    id
    employees {
      id
    }
  }
}
```

This doesn't work:

```
query {
  companies {
    ...CompanyDetail
  }
}

fragment CompanyDetail on CompanyGraph {
  id
  employees {
    id
  }
}
```

Without nested fields it does retrieve the correct information:
```
query {
  companies {
    ...CompanyDetail
  }
}

fragment CompanyDetail on CompanyGraph {
  id
  content
}
```

Things seem to fail around EfGraphQLService<TDbContext>.BuildNavigationField<TSource, TReturn>.

The item list returned by resolve seems to be null. I'm pretty sure it's because IncludeAppender.AddIncludes ignores fragments in the ResolveFieldContext.

I could try to create a pull request for this.. but it seems pretty tricky to get right for a project I'm not that familiar with.

**Comment by SimonCropp** [comment]
can you submit a PR with a failing test

**Comment by timstokman** [comment]
I'll get back to you with a set of tests.

**Comment by SimonCropp** [comment]
bump

**Comment by timstokman** [comment]
I created a pull request with a failing test. I hope it enough to open this issue again. It's been a bit hectic at work, so was a little late.
