### ISSUE TITLE
running the repo

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#4]
Hi,

Building works, trying to run the repo. I get

System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference
source: "Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets"
on hostBuilder.Build().Run(); in Program.cs

![image](https://user-images.githubusercontent.com/5032389/43371456-db3c5f3c-9392-11e8-803b-d5517a8dc604.png)

**Comment by SimonCropp** [comment]
do you have break on all exceptions turned on?

**Comment by SimonCropp** [comment]
try using IIS or express to host the sample

**Comment by flieks** [comment]
thanks, i'm on Debug, AnyCPU. Changed to IISExpress but still same error. 

It was complaining before the Test project has .net 4.7.1 which is not installed but i don't want to run that.

I also removed some git stuff which was in the csproj files. It said i had to set some git data

**Comment by SimonCropp** [comment]
does the sample run if remove the graph ql bits?

**Comment by SimonCropp** [comment]
u can also try changing the sample from netcore to full desktop runtime

**Comment by flieks** [comment]
after removing GraphQL.EntityFramework and then GraphQL it's still the same error.
it happens after builder.UseMvc(); in Startup.Configure() is executed and function returns void. 

try with new clone.

I can only set the target framework to core versions (in project props). But i guess if we change it the ef core won't work anymore.

**Comment by SimonCropp** [comment]
> after removing GraphQL.EntityFramework and then GraphQL it's still the same error.

then it looks like it not a problem related to this project. have u got the latest netcore sdk installed?

> I can only set the target framework to core versions (in project props). But i guess if we change it the ef core won't work anymore.

edit this

    <TargetFramework>netcoreapp2.1</TargetFramework>

to this
 
    <TargetFramework>net461</TargetFramework>

**Comment by SimonCropp** [comment]
given this 

> after removing GraphQL.EntityFramework and then GraphQL it's still the same error.

I will close this since it is not a problem specific to this repo

**Comment by flieks** [comment]
it works with the full version of .NET but indeed not with net core 2.1

**Comment by flieks** [comment]
Sorry for all trouble. I was using net core 2.1 preview version. 
I can confirm it works now with core 2.1 latest version
