### ISSUE TITLE
Custom Entity Key

### ISSUE THREAD

**Issue by samartzidis** [SimonCropp/GraphQL.EntityFramework#41]
According to the documentation "Currently the only supported identity member (property or field) name is Id."

Just in case, are [Key] annotations supported for specifying the entity key property? If not, any hints on what would be required to change?

Thanks.

**Comment by SimonCropp** [comment]
@samartzidis TBH i only needed Id when i build this. And that was long enough that i am not sure what complexity would be involved. Happy to accept a PR that adds the functionality
