### ISSUE TITLE
DataLoader Support?

### ISSUE THREAD

**Issue by Jonatthu** [SimonCropp/GraphQL.EntityFramework#416]
Since this library do not want to lose the scoped functionality of the dbcontext this is skipping dataloader functionality since is using serial execution.

My question is how this library is solving n+1 problems?

**Comment by SimonCropp** [comment]
> Since this library do not want to lose the scoped functionality of the dbcontext this is skipping dataloader functionality since is using serial execution.

i dont understand this statement

> My question is how this library is solving n+1 problems?

currently it makes no attempt to solve it. happy to consider a PR as a proposal
