### ISSUE TITLE
Filters "Property Path" doesn't work with nested List classes. 

### ISSUE THREAD

**Issue by Mysq** [SimonCropp/GraphQL.EntityFramework#48]
Filter "Property Path" doesn't work with nested List classes. 

For example - you want to get Companies whose Employee id equals 5.
(Actual example would be with name, but this is simpler)
It is even be reproduced with your SampleWeb project.
You write the query 
```
query{
  companies(where: {path:"Employees.Id"  comparison: equal value: "5" }){
    content
    employees{
      id
    }
  }
}
```

It does not work. 

I would expect to get All companies which have employee whose id = 5.
I've tried to fiddle around with it, I'm pretty sure the problem is in the `AggregatePath` method 
I tried just to make it work by a basic solution. 
```
var strings = path.Split('.');
var firstProperty = Expression.PropertyOrField(parameter, strings.First());
var firstPropertiesItem = Expression.Property(firstProperty, "Item", Expression.Constant(0));
var actualProperty = Expression.Property(firstPropertiesItem, strings[1]);
```
It kind of takes the right property, but doesn't seem to work, as I'm not too familiar with ExpressionTrees.
I'm a bit new to github, so I didn't do any pull requests.

**Comment by SimonCropp** [comment]
@Mysq 

yep agreed that would be a good feature.

i had a look into this. I am not sure how much effort is involved, but possibly many hours. Given i currently have no specific requirement for this feature i am unlikely to get around to it any time soon.

if you want to have a go at fixing it, here is the doco on github PRs https://help.github.com/articles/about-pull-requests/

**Comment by SimonCropp** [comment]
@Mysq do you still need this?

**Comment by Mysq** [comment]
Hi @SimonCropp, not really, I have fixed it for my small project, but it requires quite heavy modifications, and it would still require some reworking to actually put it inside your library. I can give you my code tho, if you want.

**Comment by Mysq** [comment]
Or it seems like you actually managed to do it, and way more cleanly than I did...

**Comment by SimonCropp** [comment]
Not that i know of

**Comment by Mysq** [comment]
Whats up with the all ListContains reflections and propertyAccess.

**Comment by SimonCropp** [comment]
I dont need it. So probably wont get around to it. But post the code. Someone else might find it useful

**Comment by isabekyan** [comment]
Maybe i'll dig into this in some time.
As for now we'll use separate fields for complex queries that need .Any() linq method, but they can get too plenty.

**Comment by SimonCropp** [comment]
@Mysq any update on sharing that code?

**Comment by Mysq** [comment]
This is whole `ExpressionBuilder` file, how I've did my custom solution for nested List classes. If anyone is going to use it, this was done on 1.6 release (I think) and I didn't bother to manually update the downloaded lib to 1.7 as the restructuring didn't really seem that important, so you've gotta update it a little. 

Main changes:
`BuildPredicate` is a split, most of the function code is moved to `ValidateAndBuildCompare`, which sort of duplicates to `ValidateAndBuildCompareExpression` which is used in `BuildInnerPredicate`. 
Added `BuildInnerPredicate` method where the magic happens.  
There is *some* **_code duplication_** left per se. If I had time and energy, I would remove the older `ValidateAndBuildCompare` and all the `BuildStringIn`, etc... and leave only the `BuildStringInBasicExpression` So by building basic expressions, it would make everything even more generic.
Also theres `BuildDateTimeCompare`, which I needed for my project. 
And the `WhereExpression` has `Or` and `And` parameters.

[ExpressionBuilder.zip](https://github.com/SimonCropp/GraphQL.EntityFramework/files/2864019/ExpressionBuilder.zip)

**Comment by Mysq** [comment]
[ExpressionBuilder.zip](https://github.com/SimonCropp/GraphQL.EntityFramework/files/2864198/ExpressionBuilder.zip)

This is the `ExpressionBuilder.cs` where everything is. I think it's from 1.6 release, and I didn't update, because the restructuring didn't seem too important.  

Main things that has been changed in this file:
You can send mapper dictionary, to map custom name from graphql to entity property name.
There is `Or` and `And` in WhereExpression (doesn't really change anything here tho)
`BuildPredicate` is split to itself and `ValidateAndBuildCompare` which kind of duplicates `ValidateAndBuildCompareExpression` but the latter being actually generic. 
Added `BuildInnerPredicate` where the actual magic that you need happens.
Added `BuildDateTimeCompare` the name is actually kind of misleading as its more like `DateCompare`.

Notes:
There's some code duplication **(?)** because of the way object are built for inner predicate.
Honestly, if I had more time and energy, I would remove the older versions - `BuildObjectCompare`, `BuildStringCompare` and etc. then refactor everything to use the newer more generic `BuildObjectInBasicExpression` and etc.

**Comment by Mysq** [comment]
[ExpressionBuilder.zip](https://github.com/SimonCropp/GraphQL.EntityFramework/files/2864289/ExpressionBuilder.zip)
This is the `ExpressionBuilder.cs` where everything is. I think it's from 1.6 release, and I didn't update, because the restructuring didn't seem too important.

Main things that has been changed in this file:

* You can send mapper dictionary, to map custom name from graphql to entity property name.
  There is `Or` and `And` in WhereExpression (doesn't really change anything here tho)
* `BuildPredicate` is split to itself and `ValidateAndBuildCompare` which kind of duplicates `ValidateAndBuildCompareExpression` but the latter being actually generic.
* Added `BuildInnerPredicate` where the actual magic that you need happens.
* Added `BuildDateTimeCompare` the name is actually kind of misleading as its more like `DateCompare`.

Notes:

* There's some code duplication **(?)** because of the way object are built for inner predicate.

Honestly, if I had more time and energy, I would remove the older versions - `BuildObjectCompare`, `BuildStringCompare` and etc. then refactor everything to use the newer more generic `BuildObjectInBasicExpression` and etc.

**Comment by SimonCropp** [comment]
@Mysq @isabekyan @techniq anyone want to submit a PR for this? i currently have no need for this so am unlikely to get to it any time soon
