### ISSUE TITLE
Document mutations support in readme.md

### ISSUE THREAD

**Issue by dzmitry-lahoda** [SimonCropp/GraphQL.EntityFramework#492]
donated 10 usd

**Comment by SimonCropp** [comment]
@dzmitry-lahoda what are you trying to do with mutations that isnt documented?

**Comment by dzmitry-lahoda** [comment]
How to do any mutation with this lib? Example?

**Comment by SimonCropp** [comment]
this library only extends the query side of graphql. it adds no features to the mutation side
