### ISSUE TITLE
IQueryable Select statements

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#5]
Hi Simon,

Does it only select the fields from IQueryable like [Dapper ](https://github.com/landmarkhw/Dapper.GraphQL)? Dapper seems alot of coding for each resolver so it would be nice not to have to implement Dapper.

**Comment by flieks** [comment]
super nice for navigation properties (AddNavigationField)
Why is it hard to extend this to the root query (AddQueryField) ?

**Comment by SimonCropp** [comment]
> Why is it hard to extend this to the root query (AddQueryField) ?

because this

```
.Select(x => new Employee {FirstName = x.FirstName});
```

needs to be dynamically constructed. have a look here for the type of code that needs to be written https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/GraphQL.EntityFramework/Where/ExpressionBuilder.cs

**Comment by flieks** [comment]
@SimonCropp i have a navigationField on Customer : 
```  
AddNavigationField<AddressGraph, Address>(
                name: "address",
                resolve: context => context.Source.Address);
```
And i still see all the Address fields in the sql query, although i only want Id in the request query

**Comment by flieks** [comment]
@SimonCropp It's possible for Scalar to know which fields to Select on the DBSet so we are interested in implementing this.
But what what about resolvers that want to use data from a Child (navigation) object and then return a StringGraphType for example? Or combine multiple tables to return something. 
Should we implement an attribute on the Field<> to indicate which types to Include because the include isn't executed yet. And also give property names to the attribute.

What do you suggest?

**Comment by SimonCropp** [comment]
> But what what about resolvers that want to use data from a Child (navigation) object and then return a StringGraphType for example? Or combine multiple tables to return something.

do you currently have that use case? if not i would ignore it for now

**Comment by flieks** [comment]
@SimonCropp yes we have that use case ;). 

Like for example you want to do a return Childs.Where(c => c.WonDeal).Sum(c => c.Price) 
That returns decimal and should only fetch WonDeal & Price fields.
Or even more ideally would do the Where & Sum inside the Linq to Sql Query. 

**More thoughts:**
So now only the main Query have to return DBSets where the subGraph's resolvers have already the executed data which means applying sum & where. 
Maybe there's a possibility to return some kind of Expression Type so it can be catched and included in the initial main DBSet linq query. 
Do you think it's possible ?

**Comment by SimonCropp** [comment]
Yep i think its possible

**Comment by flieks** [comment]
Interesting, i will check it in a week when i have some time

**Comment by SimonCropp** [comment]
Will close this for now. Happy to reopen if someone want to work on it

**Comment by sebitsi** [comment]
Hi @SimonCropp 

Are select (projections) implemented already ?

Will query 
```
query {
  data  {
    id,
    name
  }
}
```
execute as

`Select id, name from data
`

without all other fields in data table ?

Regards.

**Comment by SimonCropp** [comment]
@sebitsi yes but not as defined in the description above

**Comment by sebitsi** [comment]
@SimonCropp  Thanks for your response.

What do you mean by 

> yes but not as defined in the description above

Can you please explain more or point me to documentation.

If yes, how it works and what i have to do ?

Regards.

**Comment by SimonCropp** [comment]
@sebitsi you can read about defining graphs here https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/defining-graphs.md and there is a runnable sample here https://github.com/SimonCropp/GraphQL.EntityFramework/tree/master/src/SampleWeb

BTW if you intending on using the project you should note that it is required that you become a backer https://github.com/SimonCropp/GraphQL.EntityFramework#community-backed

**Comment by sebitsi** [comment]
Hi @SimonCropp.

1. I read all contents in links you provide.
   There is no answere how library handles LINQ select on subFields.
   I think library cannot handle scenario as i wrote. 
   Please tell how if this is not correct.

2. AddQueryfield is not working as expected.
   From my code:

```
public CountryGraph(IEfGraphQLService<CommonDbContext> graphQlService) : base(graphQlService)
        {
            Field(x => x.Id);
            Field(x => x.Name);
            Field(x => x.Code);
            AddQueryField(
                name: "postoffices",
                resolve: context => context.DbContext.Posts.Where(p => p.CountryID == context.Source.Id)
                ) ; 
        }
```

This config returns data, but there is n + 1 query generated in sql. 
One for all countries and n for each postofice:

```
Select * From Country
Select * From PostOffice Where CountryID = 1
Select * From PostOffice Where CountryID = 2
Select * From PostOffice Where CountryID = 3
etc
```
Is there an error in my configuration or library cannot handle it.
Please advice.

3. I will become baker if i decide to use library, Before that i need to know what library can handle and what not.

4. Do you have some roadmap about features i noticed not working ?

**Comment by SimonCropp** [comment]
sorry. in the form you want it is not supported. no there is no current plan to add that

**Comment by sebitsi** [comment]
I'm sorry to hear that,

This library has potential. 
But without this features and no roadmap i'm affraid cannot choose it for our project.

Thanks for your time.
