### ISSUE TITLE
Multiple Expressions and Expression Grouping

### ISSUE THREAD

**Issue by jrtell1** [SimonCropp/GraphQL.EntityFramework#500]
Hello!
We're using this library at my company, and we're trying to consume the GraphQL api from the frontend, however we're running into some issues.
We're trying to do a query with several `where` statements, grouped with an `or`. Basically an simple search over multiple textfields.

Now the issue, we're reading the documentation about `Multiple Expressions and Expression Grouping`, we're supposed to add the key and value `comparison: 'or'` to the grouped expression, however, the object already has a key with the exact same key (`comparison`), and the later specified key overwrites the first. How are we supposed to do a where OR?`

Thanks

**Comment by SimonCropp** [comment]
can u confirm all developers at your company are patrons https://github.com/SimonCropp/GraphQL.EntityFramework#community-backed

And i will need a solution that illustrates what you are trying to achieve to look into this

**Comment by jrtell1** [comment]
I'm sorry but none of us are.. I was hesitant to post for that very reason.. But this feels like a fundamental flaw(?), I can't see how an javascript frontend, or anyone for that matter, can seem to create a grouped where expression with `or` comparison.

We're trying to run the following query from the JS frontend:

```
query ($where: [WhereExpressionGraph]) {
  users(where: $where) {
    items {
      email
      name
    }
  }
}

```

Variables:
```
{
  "where": [
    {
      "groupedExpressions": [
        {
          "path": "email",
          "comparison": "contains",
          "value": "test",
          "comparison": "or"
        },
        {
          "path": "name",
          "comparison": "contains",
          "value": "test"
        }
      ]
    }
  ]
}
```

Note the double `comparison` keys in the first grouped expression. The first `comparison` key is overwritten by the latter. This is written as your documentation specifices, I can't help but to feel like it's something wrong? If it's a problem with the documentation or the implementation, I don't know.

**Comment by SimonCropp** [comment]
in that case can you submit this as a pull request with a failing unit test

**Comment by jrtell1** [comment]
I'm sorry but I don't know how I would do that :/

**Comment by jrtell1** [comment]
We dove into the code and eventually found the issue, it is as I kind of expected, a documentation issue.
The documentation section [Multiple Expressions and Expression Grouping
](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/doco/query-usage.md#multiple-expressions-and-expression-grouping) specifies the following: 
```
{
  entities
  (where:
    [
      {path: "Property", comparison: "startsWith", value: "Valu", negate: true},
      {
        negate: true,
        "groupedExpressions": [
          {path: "Property", comparison: "endsWith", value: "ue", comparison: "or"},
          {path: "Property", comparison: "endsWith", value: "id"}
        ]
      }
    ]
  )
  {
    property
  }
}
```
Which is wrong, the first grouped expression contains two `comparison` keys, the second key should be `connector`, like this:
```
{
  entities
  (where:
    [
      {path: "Property", comparison: "startsWith", value: "Valu", negate: true},
      {
        negate: true,
        "groupedExpressions": [
          {path: "Property", comparison: "endsWith", value: "ue", connector: "or"},
          {path: "Property", comparison: "endsWith", value: "id"}
        ]
      }
    ]
  )
  {
    property
  }
}
```
