### ISSUE TITLE
Clarify what "No null checking of nested values is done." means

### ISSUE THREAD

**Issue by sandersaares** [SimonCropp/GraphQL.EntityFramework#53]
The phrase "No null checking of nested values is done" is present in the readme, when describing "where" queries. It is not obvious what this means.

I can think of multiple interpretations:

* An intermediate value being null means the query will explode with an exception.
* An intermediate value being null means the query will treat the child value as null.
* An intermediate value being null means the query will mean the row never matches.

Possibly there are even more interpretations. Please clarify what the actual behavior is.

**Comment by SimonCropp** [comment]
An intermediate value being null means the query will explode with an exception.

**Comment by sandersaares** [comment]
Thanks for the quick response!

Is this an intentional design choice? Or a limitation of an imperfect implementation?

**Comment by SimonCropp** [comment]
No specific reason. I didnt need null checking yet so i didnt implement it.
