### ISSUE TITLE
Bidirectional Paging

### ISSUE THREAD

**Issue by mlynam** [SimonCropp/GraphQL.EntityFramework#541]
`AddQueryConnectionField` and `AddNavigationConnectionField` produce unidirectional connections. They should produce bidirectional connections.

PR with fix to follow in moments.

**Comment by mlynam** [comment]
PR #542

**Comment by mlynam** [comment]
Hey there @SimonCropp any comments or concerns about this issue and PR? I am open to critique or a conversation on the matter.

**Comment by SimonCropp** [comment]
thanks. deployed in 12.0.0-beta.3
