### ISSUE TITLE
Looks like a tag for version 11.0 is not pushed yet.

### ISSUE THREAD

**Issue by vodesoft** [SimonCropp/GraphQL.EntityFramework#549]
Please push a tag
https://github.com/SimonCropp/GraphQL.EntityFramework/releases/tag/11.0.0
The nuget package build source is not consistent.

**Comment by SimonCropp** [comment]
as per the [issue template](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

> To be using this project you (and all developer at your company) should be a [Patron](https://opencollective.com/graphqlentityframework/order/8286). See [Licensing/Patron FAQ](https://github.com/SimonCropp/graphqlentityframework/blob/master/docs/licensing-patron-faq.md). With that in mind, it is assumed anyone raising an issue is already a Patron. This process will depend on the issue quality, your circumstances, and the impact on the larger user base.

**Comment by vodesoft** [comment]
I have no problem to be a patron)) It is up to you to have 404 on links you posted.

**Comment by SimonCropp** [comment]
updated link https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/docs/licensing-patron-faq.md

**Comment by SimonCropp** [comment]
tag pushed
