### ISSUE TITLE
How to run comparisons with GraphQL.EF lib

### ISSUE THREAD

**Issue by amillioner** [SimonCropp/GraphQL.EntityFramework#554]
Hi,

can you tell me the exact syntax for running comparison with OR
this is not working for me and it gives me 

      "message": "There can be only one input field named comparison.",
        "code": "UNIQUE_INPUT_FIELD_NAMES",
        "number": "5.6.3"

Here is query:
if I remove , comparison: "OR", it works fine for me. 

{
queryEf{
    entityConnection(
      
      where:
      [
        {path: "refreshDt", comparison: "greaterThanOrEqual", value: "2010-10-19"},
        {
          groupedExpressions: [
            {path: "entityName", comparison: "endsWith", value: "ag", comparison: "OR"},
          	{path: "entityName", comparison: "contains", value: "re"}
        	]
        }
      ]
      # first: 50
      # after: "30" 
    ){
      totalCount
      pageInfo{
        startCursor,
        endCursor,
        hasNextPage,
        hasPreviousPage
      }
      items{
        entityId,
        entityName,
        entityAbbrev,
        refreshDt
      }
    }
  }
}

**Comment by SimonCropp** [comment]
can u follow all the steps in the issue template https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
