### ISSUE TITLE
Can't register some classes into Autofac container

### ISSUE THREAD

**Issue by patbush** [SimonCropp/GraphQL.EntityFramework#555]
Hi, could you expose as public classes: ComparisonGraph, ConnectorGraph, OrderBy, OrderByGraph, StringComparisonGraph? All of them are required, but we can't register them into Autofac container.

**Comment by SimonCropp** [comment]
can u re read the issue template and follow the required steps?

**Comment by SimonCropp** [comment]
https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
