### ISSUE TITLE
Improvement: supporting contributions through more maintainable code

### ISSUE THREAD

**Issue by douglasg14b** [SimonCropp/GraphQL.EntityFramework#590]
**I'm separating my reply from this thread https://github.com/SimonCropp/GraphQL.EntityFramework/issues/145, to keep things on track in that discussion.** Sorry if a new issue isn't where this should be, feel free to ask for it else wear if need be.

______________________________________________________

>@douglasg14b

>  >I could dig into EF Core, but struggling through this codebase is my hard stop, I've already been referencing it to sort out some of it's ambiguity and it's been... frustrating. (Not to rag on you Simon! Just calling out why it is undesirable, a clean and commented codebase is MUCH easier to contribute to)

>A new codebase often seems confusing when u first look at it. the problem with this project is it deal primarily with reflection and expression construction. it is not code that equates well with simplicity and ease of readability. When i find a new codebase new or daunting, i generally assume it is due to my lack of context, not a fault of the code. But that is just me. If you find ways to make it more readable, i am happy to consider pull requests.

>Also would your comment have been any less effective by omitting your critical options of the code quality

> As for commented codebase, i prefer the approach of "comment when doing something unexpected, or when the it is not clear what some code is doing". the problem is, when working on a codebase alone, and u wrote all the code, what is "not clear" is subjective, ie if i wrote some code it is difficult for me to tell when it will not be clear to someone else. And again, i am happy to accept pull requests.

__________________________________________________________

Hi Simon, I intended that to be an explanation for why I would be reluctant to contribute, I added the parenthesis after to try and provide some context.  I see you often asking for PRs, which is totally fine, I support that. However, you're reducing the contributions you might receive if your codebase is particularly difficult to jump in and modify. _This isn't an opinion, that's a fact._ E.G.: Why contribute when it may take hours just to muddle though something that is unnecessarily difficult, when the owner might be able to do it in <10mins if the solution/problem/fix is provided to them?

The majority of my work has, for better or for worse, been in other peoples code. Which has afforded me a penchant for identifying and correcting issues that affect operational efficiency, technical debt, and general longevity & maintainability. This has paid off enough for me to become a strong advocate for it with my company and clients.

Trust me, if I'm being critical, it's for good reason. I have no interest in debating emotional attachments to code, to fling insults, _or to patronize my peers_. But I am more than happy to provide critical review and solutions that can improve the quality of a codebase to encourage contributions and easier maintenance. I wouldn't call out comments if there was a distressing lack of them where it's needed the most, I'm not here for dogma, I'm here for practicality and tried and true industry practices.

______________________________________________________________

As for comments, there are two sides to that. You, the author, may not need comments as your thought process, decisions, and compromises are known to you. However, for others this is completely opaque. Applying some patterns, sticking to language stye guidelines, and implementing long-standing industry knowledge to make parameters and expectations more obvious can 100% help, but it still means anyone reading the code has to put a lot of potentially unnecessary work in to get going if even a couple things are highly ambiguous and could have been made clear with a comment.

______________________________________________________________

If you are willing and accepting, I can open a separate issue and highlight overarching issues that are largely unrelated to the complexity of the solutions you're providing. They are general, I've seen them dozens of times before. As for fixing them, that's up to you, It's unreasonable to expect a contributor to puzzle over what an ambiguous param does so they can struggle to comment it and then attempt to clean it when you know right off the top of your head. 

There is a baseline of cleansing effort the owner has to take first before effective contributions are supported by others.

**Comment by douglasg14b** [comment]
To make this clear: **Why do I care?**

Because I want to contribute, but there are some serious underlying issues that make non-trivial contributions more difficult than they need to be. Issues that only the maintainer, or others closely familiar with the project can resolve.

**Comment by SimonCropp** [comment]
thanks for the input. but i wont be accepting issues on how to improve this codebase of the people making those suggestions are unwilling to make those changes

**Comment by douglasg14b** [comment]
Hi Simon, I'm sorry to hear that. However, how do you expect a 3rd party to know things that are known, largely, only to you? Unless they have you on a voice call to query you constantly as they fill things in. I can't describe why a certain param is necessary or what the expected inputs are unless I dig deep, but you know right off the top of your head, why not write that down?

> but i wont be accepting issues on how to improve this codebase of the people making those suggestions are unwilling to make those changes

Being entirely unwilling to provide any corrections ,clarifications, or improvements, but expecting 3rd parties to do ALL them instead seems unreasonable. I'm willing to make TONS of improvements, I've done it time and time again for others, **but they have to put the first foot forward, I can't put your foot forward for you.**

Please re-read and closely consider what I said.
