### ISSUE TITLE
add sql server query logging

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#6]
Hi Simon,

I want to add sql logging to log sqlCommands executed. 

You use 
`var myDataContext = InMemoryContextBuilder.Build<MyDataContext>();`
in my other project i have this
`            services.AddDbContext<DbContextOrderStatuses>(options => options.UseLoggerFactory(factory).UseSqlServer(orderStatusConnString));
`
how can i access the DbContextOptionsBuilders ? Or should i dump InMemoryContextBuilder and use my own?

thanks

**Comment by SimonCropp** [comment]
you r in full control of the data context https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/SampleWeb/GraphQlController.cs#L34

>  Or should i dump InMemoryContextBuilder and use my own?

yes

**Comment by SimonCropp** [comment]
seems this is answered

**Comment by Intecpsp** [comment]
> you r in full control of the data context https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/SampleWeb/GraphQlController.cs#L34

Hey Simon,

    What snippet are you referring to here? I am also looking into this.

**Comment by SimonCropp** [comment]
@Intecpsp i cant seem to see you on the list of backers https://github.com/SimonCropp/GraphQL.EntityFramework#community-backed
