### ISSUE TITLE
Autofac and EfGraphQLConventions.RegisterInContainer static method

### ISSUE THREAD

**Issue by shonmisic** [SimonCropp/GraphQL.EntityFramework#62]
Currently my code for `GraphQL.EntityFramework` registration looks as per the guide:

```csharp
public void ConfigureServices(IServiceCollection services)
{
     services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
     using (var context = new MyDbContext())
     {
          EfGraphQLConventions.RegisterInContainer(services, context);
     }
     services.ConfigureNSwag();
}
```

The thing is I am also using [Autofac](https://autofac.org/) and would like to be able to do this registration inside one of the Autofac modules, but I've been having no success.

How am I to go about doing this? Also, is there a way to do this registration without calling the static `EfGraphQLConventions.RegisterInContainer` method?

**Comment by SimonCropp** [comment]
u can call this https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/src/GraphQL.EntityFramework/EfGraphQLConventions.cs#L10

or just copy the few lines in that helper method into your own autofac specific one

**Comment by SimonCropp** [comment]
@shonmisic bump
