### ISSUE TITLE
Make ArgumentProcessor public or release as separate library.

### ISSUE THREAD

**Issue by schernyh** [SimonCropp/GraphQL.EntityFramework#69]
#### Is the feature request related to a problem

For my project it would be useful to convert persisted qraphql queries to linq queries in order to implement [subscriptions](https://graphql-dotnet.github.io/docs/getting-started/subscriptions/).

#### Describe the solution

Make ArgumentProcessor public.

#### Describe alternatives considered

Release separate library in order to convert GraphQl query to IQueryable.

#### Additional context

Maybe I'm doing something horrible, but i haven't found another way to convert IQueryable to IObservable which is necessary to return from EventStreamResolvers subscribe method.

**Comment by SimonCropp** [comment]
happy to make it public.  but can u share some code of how u plan to use it? that way i can see if there are any tests i should add to ensure that use case continues to be supported  moving forward
