### ISSUE TITLE
Comparison to OData

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#7]
Hi Simon,

thanks for all the help. 

1 question: Do you see any disadvantages compared to Odata when using graphQL with your library?
[this ](https://help.nintex.com/en-us/insight/OData/HE_CON_ODATAQueryCheatSheet.htm)is a cheat sheet showing the OData features. 
Maybe only count would be missing here..

**Comment by SimonCropp** [comment]
TBH i am not fully across the OData feature set. but count is supported by graph QL via the connections feature https://github.com/SimonCropp/GraphQL.EntityFramework#response

**Comment by flieks** [comment]
Thanks alot, i read about the Connections Fields & Edge fields and they look interesting
