### ISSUE TITLE
Is it possible to use it for working without EF?

### ISSUE THREAD

**Issue by Oleg26Dev** [SimonCropp/GraphQL.EntityFramework#717]
I'd like to use GraphQL dotnet but without EF and with direct ADO.NET. Is it possible?

**Comment by Intecpsp** [comment]
I feel you're in the wrong place. This library is an extension to the graphql-dotnet library that enables . net to use the GraphQL spec. You'll want to take a look at this: https://graphql-dotnet.github.io/docs/getting-started/databases

**Comment by SimonCropp** [comment]
yeo @Intecpsp is correct

**Comment by Oleg26Dev** [comment]
Thank you, I have made it: ASP.NET app+GraphQL+ADO.NET+SQL Server without EF using. It works good.
