### ISSUE TITLE
RegisterInContainer and Entity will have errors in different assembly

### ISSUE THREAD

**Issue by programlin** [SimonCropp/GraphQL.EntityFramework#755]
RegisterInContainer and Entity will have errors in different assembly
Here is a demo - I separated the Entity in the github Sample project to another assembly, as shown in the figure below.No changes to the code.
![image](https://user-images.githubusercontent.com/16909330/142173169-13b62e62-2555-400c-b442-ff16132dfe86.png)

The following error occurs when executed
![image](https://user-images.githubusercontent.com/16909330/142173629-0c37989d-8ee1-4c10-af90-68cbe84665af.png)

As long as it is an associated property, this error will occur.
This project version is 15.0.6

**Comment by programlin** [comment]
I found the reason, the project where Entity Framework is located must enable the nullable option in the project file.

**Comment by SimonCropp** [comment]
please raise a new issue and follow the issue template
