### ISSUE TITLE
Nullability Unknown for non-nullable context

### ISSUE THREAD

**Issue by Mina-Ghaly** [SimonCropp/GraphQL.EntityFramework#767]
Hey, 

I'm trying to upgrade to dot net6 and v17.0 but I always receive an exception of Nullability Unknown for the navigation property in case the nullable context is disabled.

Actually, we are not planning to enable the nullable context at that time, so how can we do a workaround to bypass that exception?

Thanks,
Mina

**Comment by Janidbest** [comment]
I second this, we are also in the same situation.

**Comment by SimonCropp** [comment]
happy to accept a pull request that fixes this

**Comment by jurion** [comment]
I had this Issue around 1 year or so Ago. 

The solution working for me (Doesn't matter if it's .net 4.7 or .ner core or .net 5/6/7) : 

Making all navigation properties nullable with "?". We have the same files compiling for EF6 in .net 4.7 and for EfCore 7 in .Net 6. In both versions it's working. But it did remove ability to have "mandatory" navigation property. 

Example : 

![image](https://user-images.githubusercontent.com/5483208/211064615-3cc8689c-b658-4c67-9e5e-a2122095fc91.png)

This code compiles in .net 4.7, .net 5,6,7. And compatible with Ef 6, Ef core 6.7.  (And you can see warning for ? )

Same for navigation properties.

Example for a "real" navigation property

![image](https://user-images.githubusercontent.com/5483208/211064892-9cd3e8c5-06d0-4257-8984-036b3be2d656.png)


I might still have a script I did which added that "?" automaticlly to all .cs of EF context. 

It's not ideal, but it works

**Comment by SimonCropp** [comment]
happry
