### ISSUE TITLE
Demo/Sample clarifications

### ISSUE THREAD

**Issue by flieks** [SimonCropp/GraphQL.EntityFramework#8]
Hi Simon

Sorry but why did you put 2 times employees inside CompanyGraph:

```
public class CompanyGraph : EfObjectGraphType<Company>
{
    public CompanyGraph(IEfGraphQLService graphQlService) : base(graphQlService)
    {
        Field(x => x.Id);
        Field(x => x.Content);
        AddNavigationField< EmployeeGraph, Employee>(
            name: "employees",
            resolve: context => context.Source.Employees);
        AddNavigationConnectionField<EmployeeGraph, Employee>(
            name: "employeesConnection",
            resolve: context => context.Source.Employees,
            includeNames: new []{ "Employees"});
    }
}
```

**Comment by flieks** [comment]
ok i understand, cause people can choose to use edges for paging or not use edges

**Comment by flieks** [comment]
I'm trying to run a query like this in the demo:
```{
  companies(first: 2, after: "1") {
    totalCount
    edges {
      node {
        id
        content
        employees {
          id
          content
        }
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
  }
}```

I was expecting the demo to be the same as the readme ..

**Comment by flieks** [comment]
indeed, i see it thanks that works :)

I can't use `includeNames` inside AddQueryConnectionField on the root query..

**Comment by SimonCropp** [comment]
> I can't use includeNames inside AddQueryConnectionField on the root query..

yeah i couldn't think of a use case where that would be required

**Comment by flieks** [comment]
maybe because then the sample query in your readme would work ;). Its nicer to have 1 name (companies) and your code checks whether to use connection type or query type

**Comment by SimonCropp** [comment]
> maybe because then the sample query in your readme would work 

what sample in the readme? the one u listed above is not a root query

**Comment by SimonCropp** [comment]
>  Its nicer to have 1 name (companies) and your code checks whether to use connection type or query type

happy to accept a PR for that

**Comment by flieks** [comment]
this one `companies(first: 2, after: "1") {....`
where companies lives on Query (root)

Ok thanks i will do that once i have the project working in a part of our internal API.

**Comment by SimonCropp** [comment]
the doco in the readme is not meant to be a 1 to 1 mapping to the sample

**Comment by flieks** [comment]
Thanks
