### ISSUE TITLE
Add EfDocumentExecuter 

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/GraphQL.EntityFramework#89]
Add `EfDocumentExecuter` to work around

> Message: System.InvalidOperationException : A second operation started on this context before a previous operation completed. 

https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/pages/configuration.md#documentexecuter

**Comment by techniq** [comment]
👍 Thanks!  I saw this when I was migrating my codebase to GraphQL.EntityFramework from OData but ended up working around the issue at the time.

**Comment by SimonCropp** [comment]
@techniq out of curiosity how did u work around it?

**Comment by techniq** [comment]
I made 2 requests :)
