### ISSUE TITLE
Contributing Back to GraphQL.NET

### ISSUE THREAD

**Issue by RehanSaeed** [SimonCropp/GraphQL.EntityFramework#9]
GraphQL.NET connections require you to write a lot of boilerplate code right now. I raised an issue called [How Can We Simplify Creating Connections](https://github.com/graphql-dotnet/relay/issues/25) showing said boilerplate code and one potential solution to it.

When I came across your project, I thought this is another potential solition for those using EF Core or `IQueryable` in general as I don't think this project needs to be specific to EF Core. Have you considered raising a PR to contribute your `AddQueryConnectionField` code in particular back to the GraphQL.NET project?

**Comment by SimonCropp** [comment]
> Have you considered raising a PR to contribute your AddQueryConnectionField code in particular back to the GraphQL.NET project? 

Yes i did consider this. however there are a several features that rely on EF. For example

 * [EF.Functions](https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/GraphQL.EntityFramework/Where/ExpressionBuilder.cs#L122) to deliver case insensitive string comparisons
 * [.Include() syntax](https://github.com/SimonCropp/GraphQL.EntityFramework#includes-and-navigation-properties) to avoid extra round trips to the DB

There are also several features I want to build that will rely on EF. For example i would like to add some convention based mapping based on the EF model.

**Comment by RehanSaeed** [comment]
Ok, I was thinking there might be some way to decouple the EF Core code, so all that's left is `IQueryable` support.

**Comment by SimonCropp** [comment]
yeah. i actually did some research on IQueryable implementations.  https://twitter.com/SimonCropp/status/1017708227402690562

Seems most require nuanced usage similar to my usage of EF.

BTW r u using EF?

**Comment by RehanSaeed** [comment]
Right now I'm not using GraphQL.NET in production but I want to, so I've built a project template called [ASP.NET Core GraphQL Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/GraphQL.md) and submitted several PR's to the project to make it production ready which I [don't think it is](https://github.com/Dotnet-Boxed/Templates/projects/6) at the moment.

**Comment by RehanSaeed** [comment]
Eventually I'd like to use it with Microsoft Orleans personally or with EF Core at work.
