### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by skoruba** [SimonCropp/GraphQL.EntityFramework#90]
Where is the correct place to check if User has right Claims - otherwise return 401/some error message?
For example - I would like to get list of Employees only if User has claim called role: admin.
How to achieve this authorization stuff?
Thanks!

**Comment by SimonCropp** [comment]
Isnt this a question that should be raised in https://github.com/graphql-dotnet/graphql-dotnet ?  i dont think there is anything different for auth in this lib versus the core graphql lib

**Comment by skoruba** [comment]
Thanks for clarification. :)
