### ISSUE TITLE
KeyNameExtractor GetKeyNames: An item with the same key has already been added

### ISSUE THREAD

**Issue by taipignas** [SimonCropp/GraphQL.EntityFramework#989]
Hello. I am trying to set up the project for subgraph. I want to use entity framework graphql for efficient querying, but i ran into this error (after other few i resolved with the help of example project).

Hope this is enaugh information

GraphQL.EntityFramework: 27.2.0
GraphQL: 8.0.2
Microsoft.EntityFrameworkCore.SqlServer: 8.0.8

```
Exception: System.ArgumentException: An item with the same key has already been added. Key: System.Collections.Generic.Dictionary`2[System.String,System.Object]
[2024-08-27T11:35:23.727Z]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[2024-08-27T11:35:23.727Z] Executed 'Functions.DotNetGraphQuery' (Succeeded, Id=cae44f62-e280-4cd4-8975-11316368f4f3, Duration=9536ms)
[2024-08-27T11:35:23.727Z]    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
[2024-08-27T11:35:23.735Z]    at KeyNameExtractor.GetKeyNames(IModel model) in /_/src/GraphQL.EntityFramework/KeyNameExtractor.cs:line 21
[2024-08-27T11:35:23.737Z]    at GraphQL.EntityFramework.EfGraphQLService`1..ctor(IModel model, ResolveDbContext`1 resolveDbContext, ResolveFilters resolveFilters, Boolean disableTracking, Boolean disableAsync) in /_/src/GraphQL.EntityFramework/GraphApi/EfGraphQLService.cs:line 26
[2024-08-27T11:35:23.739Z]    at GraphQL.EntityFramework.EfGraphQLConventions.Build[TDbContext](ResolveDbContext`1 dbContextResolver, IModel model, ResolveFilters filters, IServiceProvider provider, Boolean disableTracking, Boolean disableAsync) in /_/src/GraphQL.EntityFramework/EfGraphQLConventions.cs:line 50
```

there are few dictionary types that are identical
`![image](https://github.com/user-attachments/assets/591cb008-2155-407f-adee-af1b59f14590)

i scaffolded my context using ef core tools
```
[ForeignKey("DocumentId")]
[InverseProperty("Documents")]
public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

[ForeignKey("DocumentId")]
[InverseProperty("Documents")]
public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
```

Many to many relation has to be configured

```
entity.HasMany(d => d.Companies).WithMany(p => p.Documents)
    .UsingEntity<Dictionary<string, object>>(
        "DocumentCompany",
        r => r.HasOne<Company>().WithMany()
            .HasForeignKey("CompanyId")
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DocumentCompanies_Companies"),
        l => l.HasOne<Document>().WithMany()
            .HasForeignKey("DocumentId")
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DocumentCompanies_DownloadDocuments"),
        j =>
        {
            j.HasKey("DocumentId", "CompanyId");
            j.ToTable("DocumentCompanies");
        });
```

or simpler config

```
builder.Entity<Document>()
    .HasMany(x => x.Companies)
    .WithMany(x => x.Documents)
    .UsingEntity("CompanyDocument");
```

More info here https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many

> Currently, EF Core uses Dictionary<string, object> to represent join entity instances for which no .NET class has been configured. However, to improve performance, a different type may be used in a future EF Core release. Do not depend on the join type being Dictionary<string, object> unless this has been explicitly configured.

**Comment by SimonCropp** [comment]
can u create a pull request with a failing unit test that replicates this problem

**Comment by taipignas** [comment]
i created a pull request https://github.com/SimonCropp/GraphQL.EntityFramework/pull/990
but i couldnt reproduce it in tests. if i run the web application it throws an error, but in the tests GetKeyNames works fine.

**Comment by SimonCropp** [comment]
sorry. without a minimal repro this will be difficult to fix

**Comment by taipignas** [comment]
if you check the pull request code you can reproduce the error. DbContextBuilder.StartAsync throws an error.

System.ArgumentException: 'An item with the same key has already been added. Key: System.Collections.Generic.Dictionary`2[System.String,System.Object]'

**Comment by taipignas** [comment]
i set up the test context. now all the tests are failing because it fails on sqlInstance.Build()

**Comment by taipignas** [comment]
thank you!
